/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.User;

/**
 *
 * @author Yunus
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    private User user;
    public AdminPanel(User user) {
        initComponents();
        this.user=user;
        initUi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SideMenuPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        labelUserPosition = new javax.swing.JLabel();
        btnHomepage = new javax.swing.JLabel();
        btnMalzemeler = new javax.swing.JLabel();
        btnDepolar = new javax.swing.JLabel();
        btnUsers = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        btnCalisanlar = new javax.swing.JLabel();
        dynamicallChangePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMİN PANEL");

        MainPanel.setBackground(java.awt.Color.white);

        SideMenuPanel.setBackground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_document_64.png"))); // NOI18N

        labelUserName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labelUserName.setText("Yunus");

        labelUserPosition.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        labelUserPosition.setForeground(new java.awt.Color(255, 51, 51));
        labelUserPosition.setText("ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(labelUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUserPosition))
        );

        btnHomepage.setBackground(new java.awt.Color(244, 67, 54));
        btnHomepage.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnHomepage.setForeground(java.awt.Color.white);
        btnHomepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-home-64.png"))); // NOI18N
        btnHomepage.setLabelFor(SideMenuPanel);
        btnHomepage.setText("ANASAYFA");
        btnHomepage.setOpaque(true);
        btnHomepage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomepageMouseClicked(evt);
            }
        });

        btnMalzemeler.setBackground(new java.awt.Color(233, 30, 99));
        btnMalzemeler.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnMalzemeler.setForeground(java.awt.Color.white);
        btnMalzemeler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-metal-64.png"))); // NOI18N
        btnMalzemeler.setLabelFor(SideMenuPanel);
        btnMalzemeler.setText("MALZEMELER");
        btnMalzemeler.setOpaque(true);
        btnMalzemeler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMalzemelerMouseClicked(evt);
            }
        });
        btnMalzemeler.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnMalzemelerKeyPressed(evt);
            }
        });

        btnDepolar.setBackground(new java.awt.Color(67, 160, 71));
        btnDepolar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnDepolar.setForeground(java.awt.Color.white);
        btnDepolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-warehouse-64.png"))); // NOI18N
        btnDepolar.setLabelFor(SideMenuPanel);
        btnDepolar.setText("STOK");
        btnDepolar.setOpaque(true);
        btnDepolar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepolarMouseClicked(evt);
            }
        });

        btnUsers.setBackground(new java.awt.Color(255, 152, 0));
        btnUsers.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnUsers.setForeground(java.awt.Color.white);
        btnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-user-group-man-man-64.png"))); // NOI18N
        btnUsers.setLabelFor(SideMenuPanel);
        btnUsers.setText("KULLANICILAR");
        btnUsers.setOpaque(true);
        btnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsersMouseClicked(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(24, 255, 255));
        btnExit.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnExit.setForeground(java.awt.Color.white);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-logout-rounded-left-64.png"))); // NOI18N
        btnExit.setLabelFor(SideMenuPanel);
        btnExit.setText("ÇIKIŞ");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        btnCalisanlar.setBackground(new java.awt.Color(57, 73, 171));
        btnCalisanlar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        btnCalisanlar.setForeground(java.awt.Color.white);
        btnCalisanlar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-staff-64.png"))); // NOI18N
        btnCalisanlar.setLabelFor(SideMenuPanel);
        btnCalisanlar.setText("ÇALIŞANLAR");
        btnCalisanlar.setOpaque(true);
        btnCalisanlar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalisanlarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SideMenuPanelLayout = new javax.swing.GroupLayout(SideMenuPanel);
        SideMenuPanel.setLayout(SideMenuPanelLayout);
        SideMenuPanelLayout.setHorizontalGroup(
            SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHomepage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMalzemeler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDepolar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCalisanlar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideMenuPanelLayout.setVerticalGroup(
            SideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideMenuPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHomepage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnMalzemeler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepolar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalisanlar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        dynamicallChangePanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(SideMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dynamicallChangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dynamicallChangePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SideMenuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsersMouseClicked
        // TODO add your handling code here:
        
        dynamicallChangePanel.removeAll();
        dynamicallChangePanel.add(new KullanicilarPanel());
        dynamicallChangePanel.revalidate();
        dynamicallChangePanel.repaint();
        
    }//GEN-LAST:event_btnUsersMouseClicked

    private void btnHomepageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomepageMouseClicked
        // TODO add your handling code here:
        dynamicallChangePanel.removeAll();
        dynamicallChangePanel.add(new Anasayfa());
        dynamicallChangePanel.revalidate();
        dynamicallChangePanel.repaint();
       
    }//GEN-LAST:event_btnHomepageMouseClicked

    private void btnDepolarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepolarMouseClicked
        // TODO add your handling code here:
        dynamicallChangePanel.removeAll();
        dynamicallChangePanel.add(new DepoPane());
        dynamicallChangePanel.revalidate();
        dynamicallChangePanel.repaint();
    }//GEN-LAST:event_btnDepolarMouseClicked

    private void btnCalisanlarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalisanlarMouseClicked
        // TODO add your handling code here:
        dynamicallChangePanel.removeAll();
        dynamicallChangePanel.add(new CalisanlarPane());
        dynamicallChangePanel.revalidate();
        dynamicallChangePanel.repaint();
    }//GEN-LAST:event_btnCalisanlarMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnMalzemelerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnMalzemelerKeyPressed
        // TODO add your handling code here:
        dynamicallChangePanel.removeAll();
        dynamicallChangePanel.add(new MalzemePane());
        dynamicallChangePanel.revalidate();
        dynamicallChangePanel.repaint();
    }//GEN-LAST:event_btnMalzemelerKeyPressed

    private void btnMalzemelerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMalzemelerMouseClicked
        // TODO add your handling code here:
        dynamicallChangePanel.removeAll();
        dynamicallChangePanel.add(new MalzemePane());
        dynamicallChangePanel.revalidate();
        dynamicallChangePanel.repaint();
    }//GEN-LAST:event_btnMalzemelerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SideMenuPanel;
    private javax.swing.JLabel btnCalisanlar;
    private javax.swing.JLabel btnDepolar;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHomepage;
    private javax.swing.JLabel btnMalzemeler;
    private javax.swing.JLabel btnUsers;
    private javax.swing.JPanel dynamicallChangePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelUserPosition;
    // End of variables declaration//GEN-END:variables

    private void initUi() {
        labelUserName.setText(user.getUserName().toUpperCase());
        if(user.getPosition()=='A'){
            labelUserPosition.setText("ADMİN");
        }else{
            labelUserPosition.setText("USER");
        }
        dynamicallChangePanel.setLayout(new java.awt.BorderLayout());
        
        
        dynamicallChangePanel.removeAll();
        dynamicallChangePanel.add(new Anasayfa());
        dynamicallChangePanel.revalidate();
        dynamicallChangePanel.repaint();
        
    }
}
