/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.Calisan;
import data.DataSource;
import data.User;
import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;
import ui.ButtonRenderer;

/**
 *
 * @author Yunus
 */
public class CalisanlarPane extends javax.swing.JPanel {

    /**
     * Creates new form CalisanlarPane
     */
    private DataSource dataSource;
    private ArrayList<Calisan> allCalisan;
    public CalisanlarPane() {
        initComponents();
        initUI();
        allCalisan=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGender = new javax.swing.ButtonGroup();
        mainPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCalisan = new org.jdesktop.swingx.JXTable();
        jLabel9 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfCalisanAdi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfSoyadi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPosition = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dPickerBaslama = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        spinMaas = new javax.swing.JSpinner();
        btnAdd = new org.jdesktop.swingx.JXButton();
        btnUpdate = new org.jdesktop.swingx.JXButton();
        lblError = new javax.swing.JLabel();
        rbtnErkek = new javax.swing.JRadioButton();
        rbtnKadin = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnClear = new org.jdesktop.swingx.JXButton();

        setBackground(java.awt.Color.white);

        mainPane.setBackground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(57, 73, 171));

        tableCalisan.setForeground(javax.swing.UIManager.getDefaults().getColor("Table.highlight"));
        tableCalisan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ADI", "SOYADI", "POSITION", "DOB", "MAAŞI", "SİL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCalisan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tableCalisan.setGridColor(java.awt.Color.black);
        tableCalisan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCalisanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCalisan);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Arama:");

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Cinzel Black", 1, 36)); // NOI18N
        jLabel15.setText("ÇALIŞANLAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        tfID.setEditable(false);
        tfID.setBackground(java.awt.Color.lightGray);

        tfCalisanAdi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Adı:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Soyadi:");

        tfSoyadi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Pozisyon:");

        cbPosition.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Müdür", "Müdür Yardımcısı", "Danışman", "Memur", "Sekreter", "Güvenlik", "Depo Sorumlusu", " ", " " }));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Başlama Tarihi:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Maaşı:");

        spinMaas.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(174, 234, 0));
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAdd.setForeground(java.awt.Color.white);
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-32.png"))); // NOI18N
        btnAdd.setText("EKLE");
        btnAdd.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAdd.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 152, 0));
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnUpdate.setForeground(java.awt.Color.white);
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-left-rotation-30.png"))); // NOI18N
        btnUpdate.setText("DÜZENLE");
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnUpdate.setMargin(new java.awt.Insets(5, 5, 5, 15));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblError.setForeground(java.awt.Color.red);
        lblError.setText("ERROR MESSAGE");

        rbtnErkek.setText("Erkek");

        rbtnKadin.setText("Kadın");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Cinsiyet:");

        btnClear.setBackground(new java.awt.Color(253, 216, 53));
        btnClear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnClear.setForeground(java.awt.Color.white);
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-clear-symbol-48.png"))); // NOI18N
        btnClear.setText("TEMİZLE");
        btnClear.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnClear.setMargin(new java.awt.Insets(5, 5, 5, 15));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSoyadi)
                            .addComponent(cbPosition, 0, 144, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCalisanAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(87, 87, 87)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dPickerBaslama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinMaas)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnErkek)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnKadin)
                                .addGap(0, 39, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblError))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCalisanAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSoyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dPickerBaslama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spinMaas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbtnErkek)
                    .addComponent(rbtnKadin))
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableCalisanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCalisanMouseClicked
        // TODO add your handling code here:
       int selectedRow = tableCalisan.getSelectedRow();
        if (allCalisan.size() > selectedRow && selectedRow >= 0) {
            Calisan temp = allCalisan.get(selectedRow);
            tfID.setText(temp.getCalisanNo() + "");
            tfCalisanAdi.setText(temp.getfName());
            tfSoyadi.setText(temp.getlName());
            cbPosition.setSelectedItem(temp.getPosition());
            spinMaas.setValue(temp.getSalary());
            dPickerBaslama.setDate(temp.getDob());
            if(temp.getCinsiyet()=='E'){
                rbtnErkek.setSelected(true);
                rbtnKadin.setSelected(false);
      
            }else{
                rbtnKadin.setSelected(true);
                rbtnErkek.setSelected(false);
            }
            Point point = evt.getPoint();
            int column = tableCalisan.columnAtPoint(point);
            if (column == 6) {
                Runnable task = () -> {
                    dataSource.openConnection();
                    dataSource.deleteCalisan(temp.getCalisanNo());
                    dataSource.closeConnection();
                    tabloDoldur("");

                };
                Thread thread = new Thread(task);
                thread.start();
        }

        //cbPosition.setSelectedItem(temp.getPosition());
        }
    }//GEN-LAST:event_tableCalisanMouseClicked

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        String search=tfSearch.getText();
        tabloDoldur(search);
    }//GEN-LAST:event_tfSearchKeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String fName = tfCalisanAdi.getText().trim();
        String lName = tfSoyadi.getText().trim();
        int index = cbPosition.getSelectedIndex();
        char gender='F';
        if(rbtnErkek.isSelected()){
            gender='E';
        }else if(rbtnKadin.isSelected()){
            gender='K';
        }
        Date baslamaTarihi=dPickerBaslama.getDate();
        int maasi=(int)spinMaas.getValue();
        if (!fName.equals("") && !lName.equals("")&& index !=-1 &&gender!='F') {
            String position=cbPosition.getSelectedItem().toString();
            Calisan calisan = new Calisan(fName,lName,baslamaTarihi,gender,position,maasi);
            Runnable task = () -> {
                dataSource.openConnection();
                boolean control = dataSource.addCalisan(calisan);
                System.out.println("Calisan Eklendi");
                dataSource.closeConnection();
                System.out.println("Thread name:" + Thread.currentThread().getName());
                if (control) {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.green);
                    lblError.setText("Calisan kayıt edildi");
                    tabloDoldur("");
                } else {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.red);
                    lblError.setText("Calisan kayıt edilirken hata oluştu");
                }
            };
            Thread thread = new Thread(task);
            thread.start();

        } else {
            lblError.setVisible(true);
            lblError.setForeground(Color.red);
            lblError.setText("Gerekli alanları doldurunuz.");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String fName = tfCalisanAdi.getText().trim();
        String lName = tfSoyadi.getText().trim();
        int index = cbPosition.getSelectedIndex();
        char gender='F';
        if(rbtnErkek.isSelected()){
            gender='E';
        }else if(rbtnKadin.isSelected()){
            gender='K';
        }
        Date baslamaTarihi=dPickerBaslama.getDate();
        int maasi=(int)spinMaas.getValue();
        if (!fName.equals("") && !lName.equals("")&& index !=-1 &&gender!='F') {
            String position=cbPosition.getSelectedItem().toString();
            int id=Integer.parseInt(tfID.getText());
            Calisan calisan = new Calisan(id,fName,lName,baslamaTarihi,gender,position,maasi);
            Runnable task = () -> {
                dataSource.openConnection();
                boolean control = dataSource.updateCalisan(calisan);
                System.out.println("Calisan Eklendi");
                dataSource.closeConnection();
                System.out.println("Thread name:" + Thread.currentThread().getName());
                if (control) {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.green);
                    lblError.setText("Calisan güncellendi");
                    tabloDoldur("");
                } else {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.red);
                    lblError.setText("Calisan güncellenirken hata oluştu");
                }
            };
            Thread thread = new Thread(task);
            thread.start();

        } else {
            lblError.setVisible(true);
            lblError.setForeground(Color.red);
            lblError.setText("Gerekli Alanları doldurunuz");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tfCalisanAdi.setText("");
        tfSoyadi.setText("");
        rbtnErkek.setSelected(false);
        rbtnKadin.setSelected(false);
        
        /*
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        FileNameExtensionFilter filter = 
        new FileNameExtensionFilter("*.Images", "jpg","png");
        jfc.addChoosableFileFilter(filter);
	jfc.setDialogTitle("Çalışan Resmini Seç");
	jfc.setFileSelectionMode(JFileChooser.APPROVE_OPTION);
        int returnValue = jfc.showSaveDialog(null);
        
	if (returnValue == JFileChooser.APPROVE_OPTION) {
	System.out.println("You selected the directory: " + jfc.getSelectedFile());
        File file=jfc.getSelectedFile();
        try {
             Image image=ImageIO.read(file);
             ivCalisanImage.setImage(image);
             ivCalisanImage.revalidate();
            } catch (IOException ex) {
            Logger.getLogger(CalisanlarPane.class.getName()).log(Level.SEVERE, null, ex);
            }    
	}
        */
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnAdd;
    private org.jdesktop.swingx.JXButton btnClear;
    private javax.swing.ButtonGroup btnGender;
    private org.jdesktop.swingx.JXButton btnUpdate;
    private javax.swing.JComboBox<String> cbPosition;
    private org.jdesktop.swingx.JXDatePicker dPickerBaslama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JPanel mainPane;
    private javax.swing.JRadioButton rbtnErkek;
    private javax.swing.JRadioButton rbtnKadin;
    private javax.swing.JSpinner spinMaas;
    private org.jdesktop.swingx.JXTable tableCalisan;
    private javax.swing.JTextField tfCalisanAdi;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSoyadi;
    // End of variables declaration//GEN-END:variables

    private void initUI() {
        lblError.setVisible(false);
        tabloDoldur("");
        tableCalisan.getColumn("SİL").setCellRenderer(new ButtonRenderer("SİL"));
    }

    private void tabloDoldur(String search) {
        dataSource = new DataSource();
        DefaultTableModel model = (DefaultTableModel) tableCalisan.getModel();
        model.setNumRows(0);
    
        Runnable task = () -> {
            dataSource.openConnection();
            allCalisan = dataSource.getAllCalisan(search);
            dataSource.closeConnection();
            if (allCalisan.size() > 0) {
                DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                for (Calisan c : allCalisan) {
                    model.addRow(new Object[]{c.getCalisanNo(),c.getfName(),c.getlName()
                    ,c.getPosition(),dateFormat.format(c.getDob()),c.getSalary()});
                }
            }
        };
        Thread thread = new Thread(task);
        thread.start();
    }
}
