/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.DataSource;
import data.User;
import java.awt.Color;
import java.awt.Point;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import ui.ButtonRenderer;

/**
 *
 * @author Yunus
 */
public class KullanicilarPanel extends javax.swing.JPanel {

    /**
     * Creates new form KullanicilarPanel
     */
    private ArrayList<User> allUser;
    private DataSource dataSource;

    public KullanicilarPanel() {
        initComponents();
        initUi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUser = new org.jdesktop.swingx.JXTable();
        jLabel9 = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfKullaniciAdi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        btnUpdate = new org.jdesktop.swingx.JXButton();
        btnAdd = new org.jdesktop.swingx.JXButton();
        lblError = new javax.swing.JLabel();
        cbPosition = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        MainPanel.setBackground(java.awt.Color.white);

        tablePanel.setBackground(new java.awt.Color(255, 152, 0));

        tableUser.setForeground(javax.swing.UIManager.getDefaults().getColor("Table.highlight"));
        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "KULLANICI ADI", "POZİSYONU", "PASSWORD", "SİL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUser.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tableUser.setGridColor(java.awt.Color.black);
        tableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableUser);
        if (tableUser.getColumnModel().getColumnCount() > 0) {
            tableUser.getColumnModel().getColumn(0).setResizable(false);
            tableUser.getColumnModel().getColumn(1).setResizable(false);
            tableUser.getColumnModel().getColumn(2).setResizable(false);
            tableUser.getColumnModel().getColumn(3).setResizable(false);
            tableUser.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("Arama:");

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Cinzel Black", 1, 36)); // NOI18N
        jLabel15.setText("KULLANICILAR");

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        sidePanel.setBackground(java.awt.Color.white);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        tfID.setEditable(false);
        tfID.setBackground(java.awt.Color.lightGray);

        tfKullaniciAdi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Kullanıcı Adı:");

        tfPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(255, 152, 0));
        btnUpdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnUpdate.setForeground(java.awt.Color.white);
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-left-rotation-30.png"))); // NOI18N
        btnUpdate.setText("DÜZENLE");
        btnUpdate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnUpdate.setMargin(new java.awt.Insets(5, 5, 5, 15));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(174, 234, 0));
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAdd.setForeground(java.awt.Color.white);
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-32.png"))); // NOI18N
        btnAdd.setText("EKLE");
        btnAdd.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAdd.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblError.setForeground(java.awt.Color.red);
        lblError.setText("ERROR MESSAGE");

        cbPosition.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cbPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "U" }));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Pozisyon:");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblError))
                    .addComponent(jLabel3))
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87)
                        .addComponent(tfID))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfKullaniciAdi))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(tfPassword)
                            .addComponent(cbPosition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUserMouseClicked
        // TODO add your handling code here:
        int selectedRow = tableUser.getSelectedRow();
        if (allUser.size() > selectedRow && selectedRow >= 0) {
            User temp = allUser.get(selectedRow);
            tfID.setText(temp.getUserNo() + "");
            tfKullaniciAdi.setText(temp.getUserName());
            tfPassword.setText(temp.getPassword());
            if (temp.getPosition() == 'A') {
                cbPosition.setSelectedIndex(0);
            } else if (temp.getPosition() == 'U') {
                cbPosition.setSelectedIndex(1);
            }
            Point point = evt.getPoint();
            int column = tableUser.columnAtPoint(point);
            if (column == 4) {
                Runnable task = () -> {
                    dataSource.openConnection();
                    dataSource.deleteUser(temp.getUserNo());
                    dataSource.closeConnection();
                    tabloDoldur("");

                };
                Thread thread = new Thread(task);
                thread.start();
        }

        //cbPosition.setSelectedItem(temp.getPosition());
        }
    }//GEN-LAST:event_tableUserMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int id = 0;
        if (!tfID.getText().equals("")) {
            id = Integer.parseInt(tfID.getText());
        }
        String name = tfKullaniciAdi.getText();
        String password = tfPassword.getText();
        int index = cbPosition.getSelectedIndex();
        char position = 'C';
        if (index == 0) {
            position = 'A';
        } else if (index == 1) {
            position = 'U';
        }

        if (!name.equals("") && !password.equals("") && (position != 'C')) {
            User user = new User(id, name, password, position, 0);
            Runnable task = () -> {
                dataSource.openConnection();
                boolean control = dataSource.updateUser(user);
                dataSource.closeConnection();
                System.out.println("Thread name:" + Thread.currentThread().getName());

                if (control) {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.green);
                    lblError.setText("Kullanıcı kayıdı güncellendi");
                    tabloDoldur("");
                } else {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.red);
                    lblError.setText("Kullanıcı kayıdı güncellenirken hata oluştu");
                }
            };
            Thread thread = new Thread(task);
            thread.start();

        } else {
            lblError.setVisible(true);
            lblError.setForeground(Color.red);
            lblError.setText("Kullanıcı adı ,password ve posizyon bilgisi giriniz");
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = tfKullaniciAdi.getText();
        String password = tfPassword.getText();
        int index = cbPosition.getSelectedIndex();
        char position = 'C';
        if (index == 0) {
            position = 'A';
        } else if (index == 1) {
            position = 'U';
        }

        if (!name.equals("") && !password.equals("") && (position != 'C')) {
            User user = new User(name, password, position);
            Runnable task = () -> {
                dataSource.openConnection();
                boolean control = dataSource.addUser(user);
                System.out.println("User Eklendi");
                dataSource.closeConnection();
                System.out.println("Thread name:" + Thread.currentThread().getName());
                if (control) {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.green);
                    lblError.setText("Kullanıcı kayıt edildi");
                    tabloDoldur("");
                } else {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.red);
                    lblError.setText("Kullanıcı kayıt edilirken hata oluştu");
                }
            };
            Thread thread = new Thread(task);
            thread.start();

        } else {
            lblError.setVisible(true);
            lblError.setForeground(Color.red);
            lblError.setText("Kullanıcı adı ,password ve posizyon bilgisi giriniz");
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        String search = tfSearch.getText();
        tabloDoldur(search);

    }//GEN-LAST:event_tfSearchKeyReleased

    private void tabloDoldur(String search) {
        dataSource = new DataSource();
        DefaultTableModel model = (DefaultTableModel) tableUser.getModel();
        model.setNumRows(0);

        Runnable task = () -> {
            dataSource.openConnection();
            allUser = dataSource.getAllEvrakUsers(search);
            dataSource.closeConnection();
            if (allUser.size() > 0) {
                allUser.forEach((e) -> {
                    String userName = "";
                    if (e.getUserName().length() > 50) {
                        userName = e.getUserName().substring(0, 49);
                    } else {
                        userName = e.getUserName();
                    }

                    model.addRow(new Object[]{e.getUserNo(), userName, e.getPosition() + "", e.getPassword()});
                });
            }
        };
        Thread thread = new Thread(task);
        thread.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private org.jdesktop.swingx.JXButton btnAdd;
    private org.jdesktop.swingx.JXButton btnUpdate;
    private javax.swing.JComboBox<String> cbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblError;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel tablePanel;
    private org.jdesktop.swingx.JXTable tableUser;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfKullaniciAdi;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

    private void initUi() {
        tabloDoldur("");
        lblError.setVisible(false);
        tableUser.getColumn("SİL").setCellRenderer(new ButtonRenderer("SİL"));
    }

}
